services:
  mysqldb:
    image: mysql
    #restart: unless-stopped
    container_name: mysqldb
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - net-data
    ports:
      - 3306:3306

  mariadb:
    image: mariadb
    #restart: unless-stopped
    container_name: mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - net-data
    ports:
      - 3307:3306

networks:
  net-data:
    name: net-data
    external: true
    driver: bridge