services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    #restart: unless-stopped
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data:/var/lib/rabbitmq
        - ./rabbitmq/log:/var/log/rabbitmq
    networks:
        - net-data

networks:
  net-data:
    name: net-data
    external: true
    driver: bridge